# -*- coding: utf-8 -*-
# 第九篇《时尚热词》词条数据
# 字段：w 终极分类词 [中, 西, 词性]；s 经典实用句 [西, 中]；e 词汇大拓展 [中, 西, 词性]

WORDS = [
    # —— 概念与风格 ——
    ("时尚", "moda", "n.f."),
    ("潮流；趋势", "tendencia", "n.f."),
    ("风格", "estilo", "n.m."),
    ("造型；形象", "look", "n.m."),
    ("穿搭；全套行头", "outfit", "n.m."),
    ("优雅的", "elegante", "adj."),
    ("别致的", "chic", "adj."),
    ("精致的", "sofisticado", "adj."),
    ("经典的", "clásico", "adj."),
    ("休闲的", "casual", "adj."),
    ("都市的", "urbano", "adj."),
    ("极简的", "minimalista", "adj."),
    ("复古风", "vintage", "adj."),
    ("波西米亚风", "boho", "adj."),
    ("运动风", "deportivo", "adj."),
    ("流行的", "popular", "adj."),
    ("过时的", "pasado de moda", "loc."),
    ("基础款", "básico", "n.m."),
    ("爆款；热门", "éxito", "n.m."),
    ("必备单品", "imprescindible", "adj."),
    ("网红；有影响力的人", "influyente", "n.m./f."),
    ("可持续的", "sostenible", "adj."),
    ("街头风", "streetwear", "n.m."),
    # —— 衣物单品 ——
    ("衣服", "ropa", "n.f."),
    ("衣物；一件衣服", "prenda", "n.f."),
    ("套装", "conjunto", "n.m."),
    ("连衣裙", "vestido", "n.m."),
    ("T恤", "camiseta", "n.f."),
    ("上衣；衬衫", "blusa", "n.f."),
    ("大衣；外套", "abrigo", "n.m."),
    ("夹克；短外套", "chaqueta", "n.f."),
    ("裤子", "pantalón", "n.m."),
    ("牛仔裤", "vaqueros", "n.m.pl"),
    ("短裤", "shorts", "n.m."),
    ("裙子", "falda", "n.f."),
    ("鞋", "zapatos", "n.m.pl"),
    ("高跟", "tacón", "n.m."),
    ("运动鞋", "tenis", "n.m.pl"),
    ("靴子", "botas", "n.f.pl"),
    ("围巾", "bufanda", "n.f."),
    ("帽子", "sombrero", "n.m."),
    ("眼镜", "gafas", "n.f.pl"),
    ("包", "bolso", "n.m."),
    ("手袋；钱包", "cartera", "n.f."),
    ("配饰；廉价首饰", "bisutería", "n.f."),
    ("珠宝", "joyas", "n.f.pl"),
    ("针织衫", "jersey", "n.m."),
    ("毛衣", "suéter", "n.m."),
    ("衬衫", "camisa", "n.f."),
    ("胸衣；文胸", "sostén", "n.m."),
    ("比基尼", "bikini", "n.m."),
    # —— 美发与妆容（米兰发型师必备）——
    ("发型", "peinado", "n.m."),
    ("剪发；发型", "corte", "n.m."),
    ("染发剂", "tinte", "n.m."),
    ("金发的", "rubio", "adj."),
    ("深色（发/肤）的", "moreno", "adj."),
    ("卷发的", "rizado", "adj."),
    ("直发的；平纹的", "liso", "adj."),
    ("化妆", "maquillaje", "n.m."),
    ("口红", "labial", "n.m."),
    ("香水", "perfume", "n.m."),
    ("美；美容", "belleza", "n.f."),
    ("皮肤；肤色", "piel", "n.f."),
    ("美容院；发廊", "salón", "n.m."),
    # —— 颜色与材质 ——
    ("印花", "estampado", "n.m."),
    ("皮革", "cuero", "n.m."),
    ("布料", "tela", "n.f."),
    ("棉", "algodón", "n.m."),
    ("丝绸", "seda", "n.f."),
    ("羊毛", "lana", "n.f."),
    ("亚麻", "lino", "n.m."),
    ("亮片；闪亮", "brillante", "adj."),
    ("透明的", "transparente", "adj."),
    ("条纹", "rayas", "n.f.pl"),
    ("格纹", "cuadros", "n.m.pl"),
    ("圆点", "lunares", "n.m.pl"),
    ("深色的", "oscuro", "adj."),
    ("浅色的", "claro", "adj."),
    # —— 版型与评价 ——
    ("显瘦的；衬托人的", "favorecedor", "adj."),
    ("紧身的", "ajustado", "adj."),
    ("宽松的", "holgado", "adj."),
    ("合身的；收腰的", "entallado", "adj."),
    ("尺码", "talla", "n.f."),
    ("贴身的", "ceñido", "adj."),
    ("舒适的", "cómodo", "adj."),
    ("昂贵的", "caro", "adj."),
    ("便宜的", "barato", "adj."),
    ("奢华的", "lujoso", "adj."),
    ("质量", "calidad", "n.f."),
    ("细节", "detalle", "n.m."),
    # —— 行业词 ——
    ("设计师", "diseñador", "n.m."),
    ("品牌", "marca", "n.f."),
    ("系列", "colección", "n.f."),
    ("时装秀", "desfile", "n.m."),
    ("天桥；T台", "pasarela", "n.f."),
    ("季节", "temporada", "n.f."),
    ("商店", "tienda", "n.f."),
    ("橱窗", "escaparate", "n.m."),
    ("打折；降价", "rebaja", "n.f."),
    ("买；购买", "comprar", "v.t."),
]

SENTENCES = [
    ("La moda siempre cambia con las estaciones.", "时尚总是随着季节变化。"),
    ("Este año la tendencia es el estilo vintage.", "今年流行的是复古风。"),
    ("Ella lleva un look muy elegante esta noche.", "今晚她穿得非常优雅。"),
    ("Los vaqueros ajustados están de moda.", "紧身牛仔裤正流行。"),
    ("Prefiero la ropa casual para el día a día.", "日常我更喜欢休闲装。"),
    ("Compré un abrigo de lana en la rebaja.", "我在打折时买了一件羊毛大衣。"),
    ("El diseñador presentó su nueva colección.", "设计师发布了他的新系列。"),
    ("El desfile de moda fue espectacular.", "那场时装秀非常精彩。"),
    ("Me gusta mucho el estilo minimalista.", "我非常喜欢极简风格。"),
    ("El bolso de cuero es muy caro.", "这个皮包非常贵。"),
    ("Ella es una influyente de moda en redes sociales.", "她是社交媒体上的时尚网红。"),
    ("El algodón es una tela muy cómoda.", "棉是一种非常舒服的面料。"),
]

EXT = [
    ("男性气质", "masculino", "adj."),
    ("女性气质", "femenino", "adj."),
    ("中性", "unisex", "adj."),
    ("年轻的；青春", "juvenil", "adj."),
    ("现代的", "moderno", "adj."),
    ("宽大的", "amplio", "adj."),
    ("防水", "impermeable", "adj."),
    ("闪亮的", "destello", "n.m."),
    ("裁缝；高级定制", "sastrería", "n.f."),
    ("配饰；附件", "accesorio", "n.m."),
    ("衣橱；衣柜", "armario", "n.m."),
    ("试穿", "probarse", "v.r."),
    ("镜子", "espejo", "n.m."),
    ("颜色", "color", "n.m."),
    ("组合；搭配", "combinar", "v.t."),
    ("丝带；蝴蝶结", "lazo", "n.m."),
    ("刺绣", "bordado", "n.m."),
    ("毛皮；皮草", "piel", "n.f."),
    ("天鹅绒", "terciopelo", "n.m."),
    ("牛仔布", "denim", "n.m."),
]
